# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload main project artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './NavyBuffalo/public'
      - name: Upload project documentation artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './NavyBuffalo/README.md'
      - name: Deploy  
        uses: actions/deploy-pages@v1
        with:
          # Deploy main artifact
          pages-directory: './NavyBuffalo/public'
          # Deploy documentation artifact
          documentation-directory: './NavyBuffalo/README.md'
          # Deploy to GitHub Pages
          deploy-to-github-pages: true
          # Deploy to GitHub Pages using the default branch
          deploy-branch: main
          # Deploy to GitHub Pages using the default repository
          deploy-repository: NavyBuffalo/NavyBuffalo
